receivers:
  otlp:
    protocols:
      grpc:
  prometheus:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  # elasticsearch/trace:
  #   endpoints: [https://localhost:9200]
  #   traces_index: trace_index

  # elasticsearch/log:
  #   endpoints: [http://localhost:9200]
  #   logs_index: my_log_index

  # otlp/elastic: 
  #   endpoint: host.docker.internal:8200
  #   tls:
  #     insecure: true
  #     insecure_skip_verify: true
  #   headers:
  #     Authorization: "Bearer zxasqw12"  

  otlp/elastic: 
    endpoint: 10.13.3.91:8200
    tls:
      insecure: true
      insecure_skip_verify: true

  logging:
  # zipkin:
  #   endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  #   format: proto

  jaeger:
    endpoint: host.docker.internal:14250
    tls:
      insecure: true

processors:
  resource:
    attributes:
    - key: deployment.environment
      action: insert
      value: development
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]